name: flutter_grits
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.37.0
  flame_tiled: ^3.1.1
  flame_tiled_utils: ^1.3.1
  vector_math: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/tiles/map1.tmx
    - assets/tiles/map1.json
    - assets/images/grits_master.png
    - assets/grits_effects.json
