# config/config.yaml
server:
  controller_port: 12345
  game_port: 8080
  dev_mode: true

matchmaker:
  host: "matcher.gritsgame.appspot.com"
  port: 80
  pairing_key: "your-pairing-key"

game:
  min_players_per_game: 1
  max_players_per_game: 8
  idle_timeout: 600 # seconds

logging:
  level: "info"
  max_log_lines: 100000